version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "backend"

  - package-ecosystem: "npm"
    # Update the directory
    directory: "/webapp"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "frontend"

  - package-ecosystem: "npm"
    # Update the directory
    directory: "/chatbot"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "backend"
