version: '3'
services:

  app_worker:
    build:
      context: .
      dockerfile: ./dependencies/Dockerfile-worker
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dev_db
      - DJANGO_SECRET_KEY=SOME_KEY
    depends_on:
      - db
      - rabbitmq

  app_web:
    build:
      context: .
      dockerfile: dependencies/app/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dev_db
      - DJANGO_SECRET_KEY=SOME_KEY
      - API_KEY=fake-key
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./app:/app/app
    restart: always

  db:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=a.roggeri.c@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5672:5672"
volumes:
  db_data:
