# Generated by Django 2.2.11 on 2020-10-10 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_patient_phone_country_code'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_holder', models.CharField(blank=True, max_length=25, verbose_name='Titular do Pagamento')),
                ('service_beneficiary', models.CharField(blank=True, max_length=25, verbose_name='Beneficiário do Serviço')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('date', models.DateField(verbose_name='Data')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.Clinic')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.TransactionType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='InflowTransaction',
        ),
    ]
