apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-app
  labels:
    app: schedul
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-app
  template:
    metadata:
      labels:
        app: schedule-app
    spec:
      containers:
        - name: schedule-app
          image: ghcr.io/andreroggeri/schedule:latest # Replaced in CI/CD pipeline
          ports:
            - containerPort: 8000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: schedule-secrets
                  key: schedule-api-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: schedule-secrets
                  key: schedule-db-url
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: schedule-secrets
                  key: schedule-django-secret-key
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: schedule-secrets
                  key: schedule-rabbitmq-url
            - name: DJANGO_SETTINGS_MODULE
              value: app.settings.staging # TODO: Use a single config file
