apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: messaging-postgres-volume-claim
  labels:
    app: messaging-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
