apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: messaging-redis-volume-claim
  labels:
    app: messaging-redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
