apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schedule-postgres-volume-claim
  labels:
    app: schedule-postgres
    app_context: schedule
    env: staging
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schedule-postgres-backup-volume-claim
  labels:
    app: schedule
    env: staging
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
