apiVersion: v1
kind: Service
metadata:
  name: schedule-postgres
  labels:
    app: schedule-postgres
    app_context: schedule
    env: staging
spec:
  ports:
    - port: 5432
  selector:
    app: schedule-postgres
