version: '3.4'

services:
  chatbot:
    build: .
    environment:
      - TEST_MODE=true
      - REDIS_URL=redis:6379
    restart: always
    volumes:
      - ./baileys_auth_info:/app/dist/baileys_auth_info

  redis:
    image: redis
    ports:
      - 6379:6379
