version: '3.4'

services:
  chatbot:
    build: .
    environment:
      - TEST_MODE=true
      - REDIS_URL=redis:6379
    restart: always
    volumes:
      - ./baileys_auth_info:/app/dist/baileys_auth_info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://chatbot:3000/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 1
      start_period: 10s

  redis:
    image: redis
    ports:
      - 6379:6379
