# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20170715_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='sg_password',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='sg_user',
        ),
    ]
