# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_dentist_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='notification_status',
            field=models.IntegerField(default=0, verbose_name='Status da notificação'),
        ),
    ]
