# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedule_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='device_token',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Token do dispositivo'),
        ),
    ]
