# Generated by Django 3.2.16 on 2022-11-22 00:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20221022_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='amil_password',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Senha AMIL'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='amil_username',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Usuário AMIL'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='TreatmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dental_plan_card_number', models.CharField(max_length=24, verbose_name='Número da carteirinha')),
                ('patient_phone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('dentist_phone', models.CharField(max_length=14, verbose_name='Telefone do dentista')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Ready'), (3, 'Canceled')], default=0, verbose_name='Status')),
                ('patient_first_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Nome do Paciente')),
                ('patient_last_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Sobrenome do Paciente')),
                ('patient_birth_date', models.DateField(blank=True, default=None, null=True, verbose_name='Data de nascimento do paciente')),
                ('patient_cpf_hash', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='CPF do paciente')),
                ('patient_gender', models.CharField(blank=True, default=None, max_length=1, null=True, verbose_name='Gênero do paciente')),
                ('dental_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.dentalplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
