# Generated by Django 3.2.16 on 2023-01-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20221222_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DATA_FETCHED_NEW_PATIENT', 'Data Fetched - New Patient'), ('DATA_FETCHED_KNOWN_PATIENT', 'Data Fetched - Known Patient'), ('DATA_FETCH_FAIL', 'Data Fetch Fail'), ('READY', 'Ready'), ('CANCELED', 'Canceled'), ('SUBMITTING', 'Submitting'), ('SUBMITTED', 'Submitted'), ('SUBMIT_FAIL', 'Submit Fail')], default='PENDING', max_length=50, verbose_name='Status'),
        ),
    ]
