name: Quality check

on:
  push:
    branches:
    - main
    paths:
      - webapp/**
  pull_request:
    # paths:
    #   - webapp/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: webapp/package-lock.json

    - name: Install dependencies
      run: npm i --ci

    - name: Lint
      run: npm run lint
    
    - name: Run tests
      run: npm run test:ci

    - name: Build
      run: npm run build:staging
