name: "Release the kraken for real"
on:
  push:
    branches:
      - release
    paths:
      - "backend/**"
      - "chatbot/**"
      - "webapp/**"
      - ".github/workflows/release.yml"

jobs:
  release-chatbot-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check changes on chatbot
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: true
          files: |
            chatbot/**
      - name: Deploy
        uses: dokku/github-action@master
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          branch: "main"
          git_remote_url: ssh://dokku@deploy.agendaodonto.com/messaging
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          git_push_flags: "--force"

  release-backend-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check changes on backend
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: true
          files: |
            backend/**
      - name: Deploy
        uses: dokku/github-action@master
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          branch: "main"
          git_remote_url: ssh://dokku@deploy.agendaodonto.com/backend
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          git_push_flags: "--force"

  release-webapp-staging:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Check changes on webapp
          id: changed-files
          uses: tj-actions/changed-files@v34
          with:
            since_last_remote_commit: true
            files: |
              webapp/**

        - name: Build
          if: steps.changed-files.outputs.any_changed == 'true'
          run: |
            cd webapp
            npm ci
            npm run build:prod

        - name: Deploy
          if: steps.changed-files.outputs.any_changed == 'true'
          uses: FirebaseExtended/action-hosting-deploy@v0
          with:
            repoToken: "${{ secrets.GITHUB_TOKEN }}"
            firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
            projectId: agendaodonto-29023
            channelId: main
            entryPoint: ./webapp

