name: "Release the kraken for real"
on:
  push:
    branches:
      - release
    paths:
      - "backend/**"
      - "chatbot/**"
      - ".github/workflows/release.yml"

jobs:
  release-chatbot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check changes on chatbot
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: true
          files: |
            chatbot/**
      - name: Deploy
        uses: dokku/github-action@master
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          branch: "main"
          git_remote_url: ssh://dokku@deploy.agendaodonto.com/messaging
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          git_push_flags: "--force"

  release-backend-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check changes on backend
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: true
          files: |
            backend/**
      - name: Deploy
        uses: dokku/github-action@master
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          branch: "main"
          git_remote_url: ssh://dokku@deploy.agendaodonto.com/backend
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          git_push_flags: "--force"
#  release-front-end-staging:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2

#  e2e-tests-staging:
#    runs-on: ubuntu-latest
#    needs: [release-backend-staging, release-front-end-staging]
#    steps:
#      - uses: actions/checkout@v2
#
#  release-front-end-production:
#    runs-on: ubuntu-latest
#    needs: [release-backend-staging, release-front-end-staging]
#    steps:
#      - uses: actions/checkout@v2
#
#  release-backend-production:
#    runs-on: ubuntu-latest
#    needs: [ release-backend-staging, release-front-end-staging ]
#    steps:
#      - uses: actions/checkout@v2
