name: 'Release the kraken'
on:
  push:
    branches:
      - main
      - backend-github-actions
    paths:
      - 'backend/**'
      - '.github/workflows/release.yml'


jobs:
  release-backend-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.DOKKU_STAGING }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          git_push_flags: '--force'

#  release-front-end-staging:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2

#  e2e-tests-staging:
#    runs-on: ubuntu-latest
#    needs: [release-backend-staging, release-front-end-staging]
#    steps:
#      - uses: actions/checkout@v2
#
#  release-front-end-production:
#    runs-on: ubuntu-latest
#    needs: [release-backend-staging, release-front-end-staging]
#    steps:
#      - uses: actions/checkout@v2
#
#  release-backend-production:
#    runs-on: ubuntu-latest
#    needs: [ release-backend-staging, release-front-end-staging ]
#    steps:
#      - uses: actions/checkout@v2