name: "Release to Staging"
on:
  push:
    branches:
      - main
      - k8s-deployment
    paths:
      - "backend/**"
      - "chatbot/**"
      - "webapp/**"
      - ".github/workflows/release.yml"
concurrency:
  group: release-staging

jobs:
  check-changed-apps:
    runs-on: ubuntu-latest
    outputs:
      changed-files-backend: ${{ steps.changed-files-backend.outputs.any_changed }}
      changed-files-chatbot: ${{ steps.changed-files-chatbot.outputs.any_changed }}
      changed-files-webapp: ${{ steps.changed-files-webapp.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check changes on backend
        id: changed-files-backend
        uses: tj-actions/changed-files@v39
        with:
          since_last_remote_commit: true
          files: |
            backend/**
            .github/**

      - name: Check changes on chatbot
        id: changed-files-chatbot
        uses: tj-actions/changed-files@v39
        with:
          since_last_remote_commit: true
          files: |
            chatbot/**
            .github/**

      - name: Check changes on webapp
        id: changed-files-webapp
        uses: tj-actions/changed-files@v39
        with:
          since_last_remote_commit: true
          files: |
            webapp/**
            .github/**

  release-backend-staging:
    needs: check-changed-apps
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency:
      group: wireguard
    if: needs.check-changed-apps.outputs.changed-files-backend == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a new version
        id: semver
        uses: cycjimmy/semantic-release-action@v4
        with:
          working_directory: "./backend"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Strip module name from version
        id: version
        if: steps.semver.outputs.new_release_published == 'true'
        run: |
          release_version=$(echo "${{ steps.semver.outputs.new_release_version }}" | sed 's/backend-//')
          echo "::set-output name=version::$release_version"

      - name: Set up QEMU
        if: steps.semver.outputs.new_release_published == 'true'
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        if: steps.semver.outputs.new_release_published == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: steps.semver.outputs.new_release_published == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Docker build
        if: steps.semver.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/andreroggeri/backend:${{ steps.version.outputs.version }},ghcr.io/andreroggeri/backend:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup wireguard
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: ${{ secrets.WG_ENDPOINT }}
          endpoint_public_key: ${{ secrets.WG_ENDPOINT_PUBLIC_KEY }}
          private_key: ${{ secrets.WG_PRIVATE_KEY }}
          ips: ${{ secrets.WG_IPS }}
          allowed_ips: ${{ secrets.WG_ALLOWED_IPS }}

      - name: Check VPN connection
        run: ping -c1 ${{ secrets.VPN_SERVER_INTERNAL_IP }}

      - name: Set context
        uses: azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Create secrets
        uses: Azure/k8s-create-secret@v5
        with:
          namespace: default
          secret-type: generic
          secret-name: schedule-secrets
          string-data: |
            {
              "schedule-api-key": "${{ secrets.SCHEDULE_API_KEY }}",
              "schedule-db-password": "${{ secrets.SCHEDULE_DB_PASSWORD }}",
              "schedule-db-url": "postgres://postgres:${{ secrets.SCHEDULE_DB_PASSWORD }}@schedule-postgres:5432/schedule",
              "schedule-django-secret-key": "${{ secrets.SCHEDULE_DJANGO_SECRET_KEY }},
              "messaging-api-key": "${{ secrets.MESSAGING_API_KEY }}",

            }

      - name: Create database deployment
        run: kubectl apply -f chatbot/deployment/postgres

      - name: Create redis deployment
        run: kubectl apply -f chatbot/deployment/redis

      - name: Create app deployment
        run: kubectl apply -f chatbot/deployment/app

      - name: Wait for deployments
        run: kubectl wait --for=condition=available --timeout=600s deployment/messaging-postgres deployment/messaging-redis deployment/messaging

      - name: Migrate database
        run: |
          kubectl port-forward service/messaging-postgres 5432:5432 &
          docker run --rm --network host -e DATABASE_URL=postgres://postgres:${{ secrets.MESSAGING_DB_PASSWORD }}@localhost:5432/messaging ghcr.io/andreroggeri/chatbot:${{ steps.version.outputs.version }} npm run db:migrate

  release-chatbot-staging:
    environment: staging
    needs: check-changed-apps
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: needs.check-changed-apps.outputs.changed-files-chatbot == 'true' && false
    concurrency:
      group: wireguard
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Generate a new version
        id: semver
        uses: cycjimmy/semantic-release-action@v4
        with:
          working_directory: "./chatbot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Strip module name from version
        id: version
        if: steps.semver.outputs.new_release_published == 'true'
        run: |
          release_version=$(echo "${{ steps.semver.outputs.new_release_version }}" | sed 's/chatbot-//')
          echo "::set-output name=version::$release_version"

      - name: Set up QEMU
        if: steps.semver.outputs.new_release_published == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.semver.outputs.new_release_published == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: steps.semver.outputs.new_release_published == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Docker build
        if: steps.semver.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./chatbot
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/andreroggeri/chatbot:${{ steps.version.outputs.version }},ghcr.io/andreroggeri/chatbot:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup wireguard
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: ${{ secrets.WG_ENDPOINT }}
          endpoint_public_key: ${{ secrets.WG_ENDPOINT_PUBLIC_KEY }}
          private_key: ${{ secrets.WG_PRIVATE_KEY }}
          ips: ${{ secrets.WG_IPS }}
          allowed_ips: ${{ secrets.WG_ALLOWED_IPS }}

      - name: Check VPN connection
        run: ping -c1 ${{ secrets.VPN_SERVER_INTERNAL_IP }}

      - name: Set context
        uses: azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Create secrets
        uses: Azure/k8s-create-secret@v5
        with:
          namespace: default
          secret-type: generic
          secret-name: messaging-secrets
          string-data: |
            {
              "messaging-api-key": "${{ secrets.MESSAGING_API_KEY }}",
              "messaging-redis-password": "${{ secrets.MESSAGING_REDIS_PASSWORD }}",
              "messaging-db-password": "${{ secrets.MESSAGING_DB_PASSWORD }}",
              "messaging-db-url": "postgres://postgres:${{ secrets.MESSAGING_DB_PASSWORD }}@messaging-postgres:5432/messaging",
              "messaging-redis-url": "redis://:${{ secrets.MESSAGING_REDIS_PASSWORD }}@messaging-redis:6379",
              "messaging-clinic-id": "${{ secrets.MESSAGING_CLINIC_ID }}",
              "schedule-api-key": "${{ secrets.SCHEDULE_API_KEY }}",
              "messaging-google-recog-api-key": "${{ secrets.MESSAGING_GOOGLE_RECOG_API_KEY }}"
            }

      - name: Create database deployment
        run: kubectl apply -f chatbot/deployment/postgres

      - name: Create redis deployment
        run: kubectl apply -f chatbot/deployment/redis

      - name: Create app deployment
        run: kubectl apply -f chatbot/deployment/app

      - name: Wait for deployments
        run: kubectl wait --for=condition=available --timeout=600s deployment/messaging-postgres deployment/messaging-redis deployment/messaging

      - name: Migrate database
        run: |
          kubectl port-forward service/messaging-postgres 5432:5432 &
          docker run --rm --network host -e DATABASE_URL=postgres://postgres:${{ secrets.MESSAGING_DB_PASSWORD }}@localhost:5432/messaging ghcr.io/andreroggeri/chatbot:${{ steps.version.outputs.version }} npm run db:migrate

  release-webapp-staging:
    needs: check-changed-apps
    if: needs.check-changed-apps.outputs.changed-files-webapp == 'true' && false
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"
          cache-dependency-path: webapp/package-lock.json

      - name: Build
        run: |
          cd webapp
          npm ci
          npm run build:staging

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_STAGING_ACCOUNT }}"
          projectId: agendaodontoweb-staging
          channelId: live
          entryPoint: ./webapp
          firebaseToolsVersion: "11.16.1"

  e2e-tests-staging:
    runs-on: ubuntu-latest
    if: false
    needs:
      [release-backend-staging, release-chatbot-staging, release-webapp-staging]
    defaults:
      run:
        working-directory: webapp
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: webapp/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run E2E
        env:
          APP_HOST: "https://staging.agendaodonto.com"
        run: npm run test:e2e
