name: "Release the kraken"
on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "chatbot/**"
      - "webapp/**"
      - ".github/workflows/release.yml"

jobs:
  release-backend-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check changes on backend
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: true
          files: |
            backend/**
      - name: Deploy
        uses: dokku/github-action@master
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          branch: "main"
          git_remote_url: ssh://dokku@deploy.agendaodonto.com/backend-staging
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          git_push_flags: "--force"

  release-chatbot-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check changes on chatbot
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: true
          files: |
            chatbot/**
      - name: Deploy
        uses: dokku/github-action@master
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          branch: "main"
          git_remote_url: ssh://dokku@deploy.agendaodonto.com/messaging-staging
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          git_push_flags: "--force"

  release-webapp-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check changes on webapp
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: true
          files: |
            webapp/**

      - name: Build
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd webapp
          npm ci
          npm run build:staging

      - name: Deploy
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_STAGING_ACCOUNT }}"
          projectId: agendaodontoweb-staging
          # projectId: agendaodonto-29023
          channelId: main
          entryPoint: ./webapp


  e2e-tests-staging:
    runs-on: ubuntu-latest
    needs: [release-backend-staging, release-chatbot-staging, release-webapp-staging]
    defaults:
      run:
        working-directory: webapp
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: webapp/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run E2E
        env:
          APP_HOST: "https://staging.agendaodonto.com"
        run: npm run test:e2e
